### ISSUE TITLE
Update for Go 1.11.1 release

### ISSUE THREAD

**Issue by novabyte** [karalabe/xgo#133]
@karalabe I think the Docker image needs an update for the new Go 1.11.1 release. I've cross-compiled for some plugins I've built and they cannot be loaded because the container image uses the Go 1.11 release while my plugins use Go 1.11.1 toolchain.
Please can you upload a new image. 👍

**Comment by karalabe** [comment]
Fixed, merged and images rebuilt :)

**Comment by novabyte** [comment]
Thanks @karalabe 🌟
