### ISSUE TITLE
“Failed to cross compile package: exit status 132”

### ISSUE THREAD

**Issue by bdesham** [karalabe/xgo#14]
I’m running OS X 10.10.2 with a clean xgo installation. When I try to compile [this simple project](https://github.com/bdesham/go-test) I get an error:

    $ xgo github.com/bdesham/go-test
    Checking docker installation...
    Client version: 1.5.0
    Client API version: 1.17
    Go version (client): go1.4.1
    Git commit (client): a8a31ef
    OS/Arch (client): darwin/amd64
    Server version: 1.5.0
    Server API version: 1.17
    Go version (server): go1.4.1
    Git commit (server): a8a31ef
    
    Checking for required docker image karalabe/xgo-latest... found.
    Cross compiling github.com/bdesham/go-test...
    Fetching github.com/bdesham/go-test...
    Compiling for linux/amd64...
    Compiling for linux/386...
    Compiling for linux/arm...
    Compiling for windows/amd64...
    Compiling for windows/386...
    Compiling for darwin/amd64...
    2015/04/07 09:57:48 Failed to cross compile package: exit status 132.

Any idea what’s wrong? No files are created in the directory where I’m running this.

(My computer is a Core i7, if that matters.)

**Comment by karalabe** [comment]
I'll take a look, but it's weird that the Go compiler doesn't output anything at all, just crashes.

**Comment by karalabe** [comment]
I'm closing this issue and non reproducible. I've added a `-v` and `-x` flags to raise verbosity, but can't debug it without being able to repro.

```
$ xgo github.com/bdesham/go-test
[...]

$ ls -al
-rwxr-xr-x  1 root     root      2238456 Sep 16 19:29 go-test-android-21-arm
-rwxr-xr-x  1 root     root      1878544 Sep 16 19:29 go-test-darwin-386
-rwxr-xr-x  1 root     root      2324096 Sep 16 19:29 go-test-darwin-amd64
-rwxr-xr-x  1 root     root      1899880 Sep 16 19:29 go-test-linux-386
-rwxr-xr-x  1 root     root      2361888 Sep 16 19:29 go-test-linux-amd64
-rwxr-xr-x  1 root     root      1957848 Sep 16 19:29 go-test-linux-arm
-rwxr-xr-x  1 root     root      2030080 Sep 16 19:29 go-test-windows-386.exe
-rwxr-xr-x  1 root     root      2493440 Sep 16 19:29 go-test-windows-amd64.exe
```
