### ISSUE TITLE
Update go to 1.11.5

### ISSUE THREAD

**Issue by kolaente** [karalabe/xgo#150]
There was a serious security flaw found in all versions prior to go 1.11.5: https://github.com/golang/go/issues/29904

So it'd be a good idea to upgrade xgo as many projects depend on it which now still also have this vulnerability because of them being built with Go 1.11.1.

**Comment by kolaente** [comment]
Also there are two prs ready to be merged which could be modified to use go 1.11.5: #149 and #145

**Comment by kolaente** [comment]
@karalabe Any updates on this?

**Comment by zgramana** [comment]
Two (user-closed) PR's have done this:

- https://github.com/karalabe/xgo/pull/153
- https://github.com/karalabe/xgo/pull/154

**Comment by rand99** [comment]
how about 1.12

**Comment by karalabe** [comment]
Published 1.11.2, 1.11.3, 1.11.4, 1.11.5 and 1.12. Docker hub will probably take a whole lot (1-2) hours to crunch through the whole queue. They also seem to be having some problems + changed a few things so I had to reconfigure the builders to work around some new errors.
