### ISSUE TITLE
Please can you add go1.13 to fix Android 10 build

### ISSUE THREAD

**Issue by ncw** [karalabe/xgo#169]
go1.12 binaries no longer work on Android 10/Q.

This was [fixed in go1.13](https://golang.org/doc/go1.13#android).

Please can you update the docker container to have go1.13

Thank you :-)

**Comment by karalabe** [comment]
Added, sorry for not maintaining this properly, it's always such a hassle to hold the hands of docker hub along every step of pushing new images.

**Comment by crazy-max** [comment]
> it's always such a hassle to hold the hands of docker hub along every step of pushing new images.

@karalabe #130

**Comment by ncw** [comment]
Thank you :-)
