### ISSUE TITLE
Is no one maintaining it?GO module support is needed.

### ISSUE THREAD

**Issue by Sloaix** [karalabe/xgo#177]
GO module support is needed.

**Comment by naiba** [comment]
可以是试一下这个 github.com/gophers/xgo

**Comment by Sloaix** [comment]
@naiba 谢谢，由于需要编译Android平台，已经妥协了。现在在GithubActions里面手动设置Gopath一下，然后把项目checkout到$gopath/src/<repo>就可以编译了。
