### ISSUE TITLE
xgo --targets=linux/amd64 .

### ISSUE THREAD

**Issue by yangjun0039** [karalabe/xgo#186]
go: writing go.sum: open /ext-go/1/src/work/go.sum268164157.tmp: read-only file system
2020/03/10 18:44:53 Failed to cross compile package: exit status 1.

**Comment by jkim-codecademy** [comment]
Can I ask what happened/what the fix was. Seeing same thing  and trying to figure it out.

**Comment by ciehanski** [comment]
I'm seeing this as well.

**Comment by yangjun0039** [comment]
execute the following to resolve:
go mod tidy

**Comment by ciehanski** [comment]
@yangjun0039 what Go version are you running? After to switching to 1.13.x it started to work for me.

**Comment by yangjun0039** [comment]
go 1.13.8 
and you can also cross-compile by docker, not xgo
