### ISSUE TITLE
Passing ldflags into the build

### ISSUE THREAD

**Issue by calmh** [karalabe/xgo#23]
It would be neat to be able to add ldflags to the build by an option to the xgo binary. Specifically I'm after being able to do `-ldflags="-w -X main.Version=v1.2.3"`.

**Comment by karalabe** [comment]
I've pushed an update to allow passing these flags (tags and linker opts) https://github.com/karalabe/xgo/commit/f2621776c8907049ffbfd0a50e7072cbb6b5a3a3. Please allow up to an hour for docker hub to crunch through the new scripts and assemble the images. Then I'd be grateful if you could test it out and report back :)

**Comment by calmh** [comment]
Will do!
