### ISSUE TITLE
packaged OS X SDK is ancient

### ISSUE THREAD

**Issue by tamird** [karalabe/xgo#25]
See: https://github.com/karalabe/xgo/blob/master/docker/base/Dockerfile#L32

This SDK version doesn't support c++11 features. Can it be updated? preferably to 10.11?

**Comment by karalabe** [comment]
Upped to 10.9 via https://github.com/karalabe/xgo/commit/841783b7fe23fbe2a0dbb2ed21164bec4851687a, please allow some time for the updates to propagate.
