### ISSUE TITLE
need ability to specify target OSX version

### ISSUE THREAD

**Issue by tamird** [karalabe/xgo#27]
See https://github.com/tpoechtrager/osxcross#deployment-target

Currently the default is 10.5 which is too old for any cgo dependency that requires c++11.

**Comment by karalabe** [comment]
Fixed in https://github.com/karalabe/xgo/commit/fc99f498a4dd174a22234792bc5a0bfe76e618e9, via `--targets=darwin-10.9`. Please allow for a few hours for the updates to roll out.
