### ISSUE TITLE
provided clang is old

### ISSUE THREAD

**Issue by tamird** [karalabe/xgo#28]
See https://github.com/tpoechtrager/osxcross/issues/53; the clang version provided by ubuntu 14.04 appears to be < 3.5, which is quite old now.

EDIT: this refers to the clang used at bootstrapping (which is also used when targeting darwin, it seems).

**Comment by karalabe** [comment]
Fixed in https://github.com/karalabe/xgo/commit/666ff21c54c77266f1f9beb1daf690df059c6691, new clang is version 3.7. Please allow a few hours for the new images to build and deploy.
