### ISSUE TITLE
Add support for GO15VENDOREXPERIMENT

### ISSUE THREAD

**Issue by janeczku** [karalabe/xgo#31]
In Go 1.5 the go command will read the environment variable GO15VENDOREXPERIMENT. If enabled, it will use the local "/vendor/" folder for dependencies.

Please add a command line flag that sets GO15VENDOREXPERIMENT=1 environmental variable in the build container.

**Comment by karalabe** [comment]
I'll add a flag to allow passing arbitrary environmental variables. Though I'm across the continent on a conference so will only be able to address this next week.

**Comment by bryanl** [comment]
@karalabe is this still something you are planning?

**Comment by captncraig** [comment]
can't you already do this with `-e GO15VENDOREXPERIMENT=1` in your docker run command?

**Comment by karalabe** [comment]
Dunno really, the vendor experiment flag is enabled by default on Go 1.6, so you can already use it by default with `--go=1.6beta1`. As the final Go 1.6 release should be done anyway in a month or so, I think there's not much benefit in complicating things with this experimental flag. Any great need for it that cannot be done with Go 1.6 (beta for now)?

**Comment by karalabe** [comment]
Closing as xgo already uses Go 1.6, featuring this.
