### ISSUE TITLE
Swig 3.0.6

### ISSUE THREAD

**Issue by dlmdata** [karalabe/xgo#39]
As of Go 1.5 .swig and .swigcxx requires Swig 3.0.6, more recent than what's in Ubuntu 15.10.

**Comment by karalabe** [comment]
Whoah, didn't see it was that old. Hmm. The next Ubuntu seems to have 3.0.8 included and should ship in about a week. Maybe it would be simpler to do a straight upgrade to that instead of hacking in a fresh SWIG.

**Comment by karalabe** [comment]
Finally found the time to update xgo to Xenial. With it, Swig was also bumped to 3.0.8 :) Should be pushed out on docker hub in a few hours.
