### ISSUE TITLE
Building fails with no errors

### ISSUE THREAD

**Issue by uniquoooo** [karalabe/xgo#41]
Hi,

Currently trying to build my Golang program which can be found [here](https://github.com/uniquoooo/dca) so I can distribute binaries without making VMs to cross-compile. I've installed the Docker Toolkit on my MacBook Pro (OSX 10.11.4) and got the Docker image downloaded. However, when I try to compile my program, it appears that everything works fine as there are no errors. When I inspect the Darwin builds they seem to have text in them:

```
!<arch>
__.PKGDEF       0           0     0     644     108       `
go object darwin amd64 go1.6 X:none
build id "b349f3108598f995f677263a00b751e7d64cc27f"

$$
package dca

$$
_go_.o          0           0     0     644     57        `
go object darwin amd64 go1.6 X:none

!
```

These are the xgo options I am using:

```
xgo \
	-out builds/dca-v0.1.0 \
	--targets=darwin/*,linux/*,windows/* \
	--deps=http://downloads.xiph.org/releases/opus/opus-1.1.2.tar.gz \
	github.com/uniquoooo/dca
```

Any ideas?

**Comment by karalabe** [comment]
Hmmm, nice :) Will look into this.

**Comment by karalabe** [comment]
Hah, found it :)

So, xgo can only build a single target, which you need to point it to. If you command, that target was actually an empty Go package, thus why it's a simple Go library object file what it produced. However if you point xgo to the proper command:

```
xgo \
    -out builds/dca-v0.1.0 \
    --targets=darwin/*,windows/* \
    --deps=http://downloads.xiph.org/releases/opus/opus-1.1.2.tar.gz \
    github.com/uniquoooo/dca/cmd/dca
```

It will result in:

```
-rwxr-xr-x  1 root     root     3082872 Apr 13 12:54 dca-darwin-10.6-386
-rwxr-xr-x  1 root     root     3719720 Apr 13 12:54 dca-darwin-10.6-amd64
-rwxr-xr-x  1 root     root     3112399 Apr 13 12:57 dca-windows-4.0-386.exe
-rwxr-xr-x  1 root     root     3845286 Apr 13 12:56 dca-windows-4.0-amd64.exe
```

There seems to be an issue with building for linux/arm though, I'll need to investigate that.

**Comment by uniquoooo** [comment]
Thanks! Seems to work now.

**Comment by karalabe** [comment]
Looked into the ARM issue. Seems that the upstream `gopus` package you are using uses some strange `pkg-config` approach to gather dependent libs on some platforms, however they seem to not return everything needed to link. I've modified xgo to gather `pkg-config` stuff, but my bet is that it also needs some fixes in `gopus` to make it build when it hits this file: https://github.com/layeh/gopus/blob/master/opus_shared.go
