### ISSUE TITLE
"osxcross: error: cannot find libc++ headers" when compiling for darwin-10.9/amd64

### ISSUE THREAD

**Issue by tschottdorf** [karalabe/xgo#44]
This worked (presumably) until de9b3d3 landed a few hours ago.

https://github.com/cockroachdb/cockroach/issues/6030

```
Digest: sha256:709a6d3bbd1625e10e75352e165ecfb3207c7d87eb7113f4a7873a5589cbc8ac
Status: Downloaded newer image for karalabe/xgo-1.6:latest
2016/04/13 13:03:43 Failed to access GOPATH element /home/ubuntu/.go_workspace/src/github.com/cockroachdb/cockroach/test-binaries.f3Le: open /home/ubuntu/.go_workspace/src/github.com/cockroachdb/cockroach/test-binaries.f3Le: permission denied
Cross compiling github.com/cockroachdb/cockroach...
Building locally github.com/cockroachdb/cockroach...
Compiling for darwin-10.9/amd64...
# github.com/cockroachdb/cockroach/util
osxcross: error: cannot find libc++ headers
osxcross: error: while detecting target
# github.com/cockroachdb/cockroach/util/tracing
osxcross: error: cannot find libc++ headers
osxcross: error: while detecting target
# github.com/cockroachdb/c-snappy
osxcross: error: cannot find libc++ headers
osxcross: error: while detecting target
# github.com/cockroachdb/c-protobuf
osxcross: error: cannot find libc++ headers
osxcross: error: while detecting target
# github.com/elastic/gosigar
osxcross: error: cannot find libc++ headers
osxcross: error: while detecting target
Error deleting container: Error response from daemon: Driver btrfs failed to remove root filesystem 4276ebe92c506d407bb42469fe772c590ada6ed964de1944eb55f6a5d0813634: Failed to destroy btrfs snapshot /var/lib/docker/btrfs/subvolumes for a78b3369092bd99400355034d06dcb5aa96dbed6b738ae72cd06bb4cdcf9e5a6: operation not permitted
2016/04/13 13:04:08 Failed to cross compile package: exit status 2.
```

The README indicates it should work for
> OSX APIs in the range of 10.6 - 10.11

which indicates that something went wrong.

**Comment by tschottdorf** [comment]
Unfortunately, building for `darwin-10.11` does not fix the issue (same errors).

**Comment by tschottdorf** [comment]
Here's the output with `-x -v` (for `darwin-10.11`):
https://gist.github.com/tschottdorf/d44f3f2edea9f454aee0b82178372bb2

**Comment by tschottdorf** [comment]
A more compact failing invocation is

`xgo --targets=darwin-10.11/amd64 --go=1.6 github.com/elastic/gosigar`

**Comment by karalabe** [comment]
Ufff, dang. I'll take a look.

**Comment by tschottdorf** [comment]
Thanks, appreciated. Let me know if I can help.

**Comment by karalabe** [comment]
Hmmm, seems that Apple moved `/usr/include/c++/v1` out of the SDK on 10.11 :| Not sure how to work around it yet.

**Comment by tamird** [comment]
Looks like there's some relevant discussion in https://github.com/Valloric/ycmd/issues/254

**Comment by karalabe** [comment]
Already testing the fix :)

**Comment by karalabe** [comment]
$ xgo --targets=darwin-10.11/amd64 --go=1.6.1 github.com/elastic/gosigar
$ ls -al
-rw-r--r--  1 root     root     314650 Apr 13 18:33 gosigar-darwin-10.11-amd64

**Comment by tschottdorf** [comment]
Cool. If you don't mind, try against `github.com/cockroachdb/cockroach` as well (should take <15min).

**Comment by karalabe** [comment]
Just did, something failed but I'm doing a second pass now.

**Comment by karalabe** [comment]
Ok, an hour of debug later I realized that 10.6 doesn't have c++11 :P Building now with 10.11 to see it my fix was actually good all along.

**Comment by karalabe** [comment]
```
-rwxr-xr-x  1 root     root     37627320 Apr 13 19:18 cockroach-darwin-10.11-amd64
```

**Comment by tschottdorf** [comment]
:+1:

**Comment by karalabe** [comment]
Fixed by https://github.com/karalabe/xgo/commit/647f256c447ee20f9bf13ebc42e612d55994a383 :) 

I've polished up the patch a bit, did a second run against cockroach with 10.9. All green.

```
-rwxr-xr-x  1 root     root     37627320 Apr 13 19:18 cockroach-darwin-10.11-amd64
-rwxr-xr-x  1 root     root     37627320 Apr 13 19:32 cockroach-darwin-10.9-amd64
```

I've pushed the changes. Please allow up to a few hours for docker hub to crunch through the changes and see if this resolves the issue. Please leave this ticket open until then :)

Thanks for the report!

**Comment by tschottdorf** [comment]
Thanks for the fix! Btw, I don't see any testing in this repo - it's easy enough to set up (at least on CircleCI, but probably also on TravisCI and others at this point). See https://github.com/cockroachdb/cockroach/blob/master/build/build-osx.sh (which is what we call from our `circle.yml`)

**Comment by tschottdorf** [comment]
works locally, thanks!

**Comment by karalabe** [comment]
@tschottdorf I wrote a small test suite for xgo to run before pushing out new changes. I've added a few smoke tests, all the [`go-ethereum`](https://github.com/ethereum/go-ethereum) builds as well as the `darwin-10.9/amd64` build of cockroachdb. Are you guys using xgo for other platforms too? I'd gladly add them to my test suite to ensure I don't screw up your builds next time I develop something :)

**Comment by tschottdorf** [comment]
Thanks Péter! darwin-10.9/amd64 is currently all we're building (with xgo).
We'll make sure to let you know when we're tackling other platforms.
