### ISSUE TITLE
Support for go 1.9

### ISSUE THREAD

**Issue by coryb** [karalabe/xgo#89]
Hello,  

I am using xgo to build and release several of my projects and would like to start using go 1.9 features and fixes, unfortunately when I try with `xgo --go 1.9` I get:
```
Checking for required docker image karalabe/xgo-1.9... not found!
```
I am not sure what is involved in getting a new xgo supported version, hopefully it is not too hard, or perhaps you can point me in a direction to help provide you a PR?

Thanks for xgo, it has been extremely useful!

**Comment by adg** [comment]
Is there anything I can do to help push this forward?

**Comment by lixingwang** [comment]
+1, waiting for the PR to be merged, please make it forward.
