### ISSUE TITLE
Howto use the xgo wrapper?

### ISSUE THREAD

**Issue by andig** [karalabe/xgo#97]
I'm trying to use xgo from crosscompiling filebeats on OSX. I've used homebrew to install go, pulled the docker image (and have docker installed) then 

    go get github.com/karalabe/xgo

which returns nothing. `xgo` is still not recognized as a command.

What am I doing wrong here?

**Comment by protenhan** [comment]
I don't know if you found out by yourself yet but ```go get github.com/karalabe/xgo``` will install xgo to ```~/go/bin/```. 
You can just add ~/go/bin to your PATH and you're good to go 🙂
